### ISSUE TITLE
The "Bounce (canvas)" example is broken

### ISSUE THREAD

**Issue by MrEfrem** [ballercat/walt#46]
# Bug Report
## Overview
The "Bounce (canvas)" example is throwing the error and anything isn't showing.

## Expected
The working example.

## Actual
```
Uncaught CompileError: WasmCompile: Compiling wasm function #7:<?> failed: immutable global #0 cannot be assigned @+673
    at compile (eval at Explorer.compileAndRun (https://ballercat.github.io/walt/dist/explorer.js:51252:24), <anonymous>:21:22)
    at Explorer.compileAndRun (https://ballercat.github.io/walt/dist/explorer.js:51254:23)
    at CallbackQueue.notifyAll (https://ballercat.github.io/walt/dist/explorer.js:14553:22)
    at ReactUpdatesFlushTransaction.close (https://ballercat.github.io/walt/dist/explorer.js:2148:24)
    at ReactUpdatesFlushTransaction.closeAll (https://ballercat.github.io/walt/dist/explorer.js:6095:25)
    at ReactUpdatesFlushTransaction.perform (https://ballercat.github.io/walt/dist/explorer.js:6042:16)
    at ReactUpdatesFlushTransaction.perform (https://ballercat.github.io/walt/dist/explorer.js:2178:32)
    at Object.flushBatchedUpdates (https://ballercat.github.io/walt/dist/explorer.js:2261:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (https://ballercat.github.io/walt/dist/explorer.js:6095:25)
    at ReactDefaultBatchingStrategyTransaction.perform (https://ballercat.github.io/walt/dist/explorer.js:6042:16)
```

**Comment by MrEfrem** [comment]
Here error is appears:
 https://github.com/ballercat/walt/blob/1567fd0ada8eceeeb11bb3f595982ec74f0099f8/docs/src/examples/walt/animation.walt#L19
If I try to change `const` on the `let` then I get the other error:
```
Uncaught CompileError: WasmCompile: Compiling wasm function #5:<?> failed: set_global found empty stack @+238
    at compile (eval at Explorer.compileAndRun (webpack-internal:///636), <anonymous>:21:22)
    at Explorer.compileAndRun (webpack-internal:///636:58:23)
    at CallbackQueue.notifyAll (webpack-internal:///283:76:22)
    at ReactUpdatesFlushTransaction.close (webpack-internal:///41:59:24)
    at ReactUpdatesFlushTransaction.closeAll (webpack-internal:///107:209:25)
    at ReactUpdatesFlushTransaction.perform (webpack-internal:///107:156:16)
    at ReactUpdatesFlushTransaction.perform (webpack-internal:///41:89:32)
    at Object.flushBatchedUpdates (webpack-internal:///41:172:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (webpack-internal:///107:209:25)
    at ReactDefaultBatchingStrategyTransaction.perform (webpack-internal:///107:156:16)
compile @ VM32900:21
Explorer.compileAndRun @ app.js?bd9c:47
notifyAll @ CallbackQueue.js?9924:76
close @ ReactUpdates.js?15fe:59
closeAll @ Transaction.js?57ab:209
perform @ Transaction.js?57ab:156
perform @ ReactUpdates.js?15fe:89
flushBatchedUpdates @ ReactUpdates.js?15fe:172
closeAll @ Transaction.js?57ab:209
perform @ Transaction.js?57ab:156
batchedUpdates @ ReactDefaultBatchingStrategy.js?3379:62
enqueueUpdate @ ReactUpdates.js?15fe:200
enqueueUpdate @ ReactUpdateQueue.js?f524:24
enqueueCallback @ ReactUpdateQueue.js?f524:122
ReactComponent.setState @ ReactBaseClasses.js?352f:66
requestAnimationFrame @ app.js?bd9c:69
setTimeout (async)
Promise.resolve.then.catch.e @ app.js?bd9c:55
Promise rejected (async)
Explorer.compileAndRun @ app.js?bd9c:51
notifyAll @ CallbackQueue.js?9924:76
close @ ReactUpdates.js?15fe:59
closeAll @ Transaction.js?57ab:209
perform @ Transaction.js?57ab:156
perform @ ReactUpdates.js?15fe:89
flushBatchedUpdates @ ReactUpdates.js?15fe:172
closeAll @ Transaction.js?57ab:209
perform @ Transaction.js?57ab:156
batchedUpdates @ ReactDefaultBatchingStrategy.js?3379:62
enqueueUpdate @ ReactUpdates.js?15fe:200
enqueueUpdate @ ReactUpdateQueue.js?f524:24
enqueueCallback @ ReactUpdateQueue.js?f524:122
ReactComponent.setState @ ReactBaseClasses.js?352f:66
requestAnimationFrame @ app.js?bd9c:69
requestAnimationFrame (async)
setState @ app.js?bd9c:65
notifyAll @ CallbackQueue.js?9924:76
close @ ReactUpdates.js?15fe:59
closeAll @ Transaction.js?57ab:209
perform @ Transaction.js?57ab:156
perform @ ReactUpdates.js?15fe:89
flushBatchedUpdates @ ReactUpdates.js?15fe:172
closeAll @ Transaction.js?57ab:209
perform @ Transaction.js?57ab:156
batchedUpdates @ ReactDefaultBatchingStrategy.js?3379:62
enqueueUpdate @ ReactUpdates.js?15fe:200
enqueueUpdate @ ReactUpdateQueue.js?f524:24
enqueueCallback @ ReactUpdateQueue.js?f524:122
ReactComponent.setState @ ReactBaseClasses.js?352f:66
Explorer.handleRun.debounce @ app.js?bd9c:62
later @ app.js?bd9c:25
setTimeout (async)
(anonymous) @ app.js?bd9c:29
apply @ _apply.js?6bec:15
baseInvoke @ _baseInvoke.js?fe34:21
apply @ _apply.js?6bec:16
(anonymous) @ _overRest.js?a971:32
MenuItem._this.handleClick @ MenuItem.js?279b:38
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js?424d:69
executeDispatch @ EventPluginUtils.js?6850:85
executeDispatchesInOrder @ EventPluginUtils.js?6850:108
executeDispatchesAndRelease @ EventPluginHub.js?50a9:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js?50a9:54
forEachAccumulated @ forEachAccumulated.js?5b44:24
processEventQueue @ EventPluginHub.js?50a9:254
runEventQueueInBatch @ ReactEventEmitterMixin.js?4951:17
handleTopLevel @ ReactEventEmitterMixin.js?4951:27
handleTopLevelImpl @ ReactEventListener.js?8960:72
perform @ Transaction.js?57ab:143
batchedUpdates @ ReactDefaultBatchingStrategy.js?3379:62
batchedUpdates @ ReactUpdates.js?15fe:97
dispatchEvent @ ReactEventListener.js?8960:147
```

**Comment by ballercat** [comment]
Hey,

Thanks, definitely a regression. 

Looks like it's this exact line: https://github.com/ballercat/walt/blob/master/docs/src/examples/walt/animation.walt#L25

The imported function probably not encoded correctly, most likely not returning a value.  Happened before on a dev branch, so it's probably time for a unit test.

**Comment by ballercat** [comment]
Was able to reproduce it and It looks like the global index is not calculated correctly.
